### PR TITLE
#11 Add syncdb command.

### PR DESCRIPTION
**Pull request by hkirsman**
## Overview

In Lando we have syncdb command that imports production database via SSH tunnel and imports the db into local env. This is adding the same feature to this project.

The logic of the script:

1. it's based on  https://github.com/wunderio/unisport/blob/master/.lando/syncdb.sh
2. cr and other tasks are done in the post db script https://github.com/wunderio/ddev-drupal/pull/12/files#diff-858ae242bb89b1f7b21f07c96a99602c883ecb253d0a24a27af902e1d52ab807
3. instead of using @prod alias we use ssh command as for some reason drush alias just times out
4. with ssh we download the db and then import that, after everything is done we remove the the file.

## Testing

1. Install this version where you have SILTA support and you know `lando syncdb` works in Lando:

```
ddev composer require wunderio/ddev-drupal:dev-feature/11-Create-syncdb-task-to-sync-wunder-production-db-to-local --dev
```

2. Try syncdb
`ddev syncdb`

### CODE REVIEW

**Comment by hkirsman** [comment]
Based on @deiviic comment I've added skipping of cache tables in the import. In one of the real case scenarios the difference of dump file was from 517MB to 86MB.

**Comment by artursv** [comment]
> instead of dropping the db

Do we have to drop it? At lando clears DB before doing import - have not checked if ddev does the same.

**Comment by hkirsman** [comment]
> > instead of dropping the db
> 
> Do we have to drop it? At lando clears DB before doing import - have not checked if ddev does the same.

Yeah, we don't need extra drop. I've tested that import works fine without extra drop and there's also extra command not to drop 

image

**Review by deiviic — APPROVED** [review]

**Review by ragnarkurmwunder — APPROVED** [review]
Good!

**Pull request merged**
